name: quizapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  random_string: ^2.3.1
  shared_preferences: ^2.1.2
  image_picker: ^1.0.1+1
  firebase_storage: ^12.3.7
  http: ^1.2.2
  cloudinary: ^1.2.0
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.2.1
  google_sign_in: ^6.2.2
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.3
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.1
  flutter_native_splash: ^2.4.4
  path_provider: ^2.1.5
  animated_text_kit: ^4.2.2
  flutter_launcher_icons: ^0.14.2
  lottie: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#FFFFFF" # Background color
  image: assets/images/aa.gif # Path to the logo
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - .env
